# This workflow analyses and tests every pull request.
name: Pull Request Validation
on: 
  pull_request:
  workflow_run:
    workflows: [a]
    types:
      - completed

jobs:
  analyze_code_before_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
          channel: 'stable'

      - name: Installs the dependencies
        run: flutter pub get
    
